/**
 * Bilingual copy for the "Plan My Day" experience.
 *
 * Kept in one typed module (rather than the remote-editable react-intl bundle)
 * because the planner needs dozens of tightly-coupled strings — questions,
 * option blurbs, reason templates and persona names — that must always ship
 * complete in both languages.
 */
const en = {
  tab: 'Plan',
  hero: {
    eyebrow: 'Personal day planner',
    title: 'Tell us who you are.\nWe design the day.',
    subtitle:
      'A handful of quick questions about your crew, your energy and your budget — then Francisco’s planner builds a real itinerary from the live excursion catalogue, priced for your exact group.',
    start: 'Start planning',
    resume: 'Resume my plan',
    browse: 'Browse the catalogue instead',
    minutes: '≈ 90 seconds · 12 questions · no signup',
    bullets: [
      { emoji: '🧭', title: 'Reads your crew', text: 'Ages, energy, swimmers, early risers — all of it shapes the shortlist.' },
      { emoji: '🧮', title: 'Real prices', text: 'Every tour is priced from the live catalogue for your exact adults and children.' },
      { emoji: '🗓️', title: 'A day that works', text: 'No two 10-hour tours stacked on one day. Slots, pace and travel time all check out.' },
    ],
  },
  ui: {
    back: 'Back',
    next: 'Continue',
    skip: 'Skip this',
    stepOf: (a: number, b: number) => `Step ${a} of ${b}`,
    startOver: 'Start over',
    editAnswers: 'Edit answers',
    yourProfile: 'Your profile',
    seePlan: 'Build my day',
    optional: 'Optional',
    pickUpTo: (n: number) => `Pick up to ${n}`,
    pickAtLeastOne: 'Pick at least one to continue',
    selected: 'Selected',
    adults: 'Adults',
    children: 'Children',
    kidsAges: 'How old are the kids?',
    tapToEdit: 'Tap any chip to change your answer',
    keyboardHint: 'Tip: press 1–9 to choose, Enter to continue',
  },
  questions: {
    partyType: {
      title: 'Who is coming to the Caribbean?',
      hint: 'This shapes everything from boat choice to how long a day should run.',
      options: {
        solo: { label: 'Just me', desc: 'Solo traveller, free to say yes to anything', emoji: '🧍' },
        couple: { label: 'The two of us', desc: 'A couple sharing the day', emoji: '💞' },
        family: { label: 'Family with kids', desc: 'Parents plus children on board', emoji: '👨‍👩‍👧' },
        friends: { label: 'Friends group', desc: 'A crew that travels loud', emoji: '🥂' },
        multigen: { label: 'Several generations', desc: 'Grandparents, parents and kids together', emoji: '👵' },
      },
    },
    headcount: {
      title: 'How many of you?',
      hint: 'Prices below are calculated per head, with real child rates where the tour offers them.',
    },
    adultAge: {
      title: 'Where are the grown-ups on the age map?',
      hint: 'Nobody gets carded — it only tunes pace and comfort.',
      options: {
        young: { label: '18 – 29', desc: 'Late nights welcome, sleep is optional', emoji: '🔥' },
        prime: { label: '30 – 44', desc: 'Adventure by day, good dinner by night', emoji: '🌞' },
        mature: { label: '45 – 59', desc: 'Great experiences, comfortable logistics', emoji: '🌴' },
        senior: { label: '60 +', desc: 'Beauty and ease over rough terrain', emoji: '🕊️' },
      },
    },
    energy: {
      title: 'How wild should this day be?',
      hint: 'Slide from hammock-slow to full adrenaline.',
      scale: [
        { label: 'Barefoot slow', desc: 'Sand, shade, long lunches' },
        { label: 'Easy going', desc: 'Gentle activity, plenty of rest' },
        { label: 'Balanced', desc: 'A bit of thrill, a bit of chill' },
        { label: 'Pretty adventurous', desc: 'Mud, speed, heights — bring it' },
        { label: 'Full send', desc: 'Maximum adrenaline, minimum sitting' },
      ],
    },
    interests: {
      title: 'What pulls you in?',
      hint: 'Choose up to five. The planner weighs these hardest.',
    },
    aim: {
      title: 'What do you want to take home?',
      hint: 'The feeling that matters most when you land back home.',
      options: {
        stories: { label: 'Stories to tell', desc: 'Days worth retelling for years', emoji: '📖' },
        unwind: { label: 'Deep rest', desc: 'Come back genuinely recharged', emoji: '🧘' },
        together: { label: 'Time together', desc: 'The group actually connecting', emoji: '🫶' },
        adrenaline: { label: 'A racing heart', desc: 'Adrenaline you can still feel', emoji: '⚡' },
        romance: { label: 'Romance', desc: 'Just the two of you, beautifully', emoji: '💫' },
        discover: { label: 'The real island', desc: 'Culture, people, flavours', emoji: '🧭' },
        party: { label: 'A legendary night', desc: 'Music, dancing, until late', emoji: '🪩' },
      },
    },
    dayShape: {
      title: 'How full should a day feel?',
      hint: 'We stack experiences only where the timing genuinely works.',
      options: {
        signature: { label: 'One signature experience', desc: 'A single unforgettable excursion, unhurried', emoji: '💎' },
        balanced: { label: 'Two per day', desc: 'A main event plus a second highlight', emoji: '⚖️' },
        packed: { label: 'Three per day', desc: 'Morning, afternoon and night in motion', emoji: '🔋' },
        max: { label: 'Fill it up', desc: 'Squeeze in everything the clock allows', emoji: '🚀' },
      },
    },
    days: {
      title: 'How many days shall we plan?',
      hint: 'More days means more variety — never the same coast twice.',
      unit: 'days',
    },
    budget: {
      title: 'What is comfortable per person, per day?',
      hint: 'Excursion tickets only. Nothing gets padded on top.',
      options: {
        value: { label: 'Up to $80', desc: 'Best value picks that still feel special', emoji: '🌱' },
        balanced: { label: '$80 – $150', desc: 'The sweet spot for most travellers', emoji: '⭐' },
        premium: { label: '$150 – $260', desc: 'Premium tiers, VIP areas, lobster', emoji: '👑' },
        open: { label: 'Budget is open', desc: 'Show me the very best regardless', emoji: '💎' },
      },
    },
    transport: {
      title: 'How do you want to move?',
      hint: 'Every excursion already includes hotel pick-up. Private wheels are an upgrade.',
      options: {
        included: { label: 'Shared pick-up is fine', desc: 'Included hotel transfer with the tour group', emoji: '🚐' },
        private_day: { label: 'Private vehicle for the day', desc: 'Your own driver waiting between stops', emoji: '🚙' },
        private_full: { label: 'Private everything', desc: 'Airport arrival, departure and every excursion day', emoji: '🛬' },
      },
    },
    constraints: {
      title: 'Anything we should plan around?',
      hint: 'Honest answers make the plan better. Skip if nothing applies.',
      options: {
        non_swimmer: { label: 'Weak or non-swimmers', desc: 'Keep deep-water swimming optional', emoji: '🛟' },
        seasick: { label: 'Sea-sickness', desc: 'Avoid long boat crossings', emoji: '🌊' },
        limited_mobility: { label: 'Limited mobility', desc: 'No rough trails or climbing', emoji: '🦯' },
        no_early: { label: 'No early mornings', desc: 'Skip the sunrise departures', emoji: '⏰' },
        no_alcohol: { label: 'No alcohol', desc: 'Open-bar tours are less relevant', emoji: '🚫' },
        early_nights: { label: 'Early nights', desc: 'Nothing that runs past bedtime', emoji: '🌙' },
        sun_sensitive: { label: 'Sun sensitive', desc: 'Prefer shade and shorter exposure', emoji: '🧴' },
      },
    },
    occasion: {
      title: 'Are we celebrating something?',
      hint: 'Francisco likes to know — it changes the little touches.',
      options: {
        none: { label: 'Just a great trip', desc: 'No occasion needed', emoji: '🌴' },
        honeymoon: { label: 'Honeymoon', desc: 'Newlyweds on the water', emoji: '💍' },
        anniversary: { label: 'Anniversary', desc: 'Marking the years together', emoji: '🥂' },
        birthday: { label: 'Birthday', desc: 'Somebody turns a year braver', emoji: '🎂' },
        bachelor: { label: 'Bachelor / bachelorette', desc: 'The last big one before the vows', emoji: '🎉' },
        reunion: { label: 'Family reunion', desc: 'Everyone in one place at last', emoji: '🏡' },
      },
    },
    logistics: {
      title: 'Last details',
      hint: 'Both optional — they simply make Francisco’s reply faster.',
      dateLabel: 'First day of the plan',
      zoneLabel: 'Hotel or area',
      zonePlaceholder: 'e.g. Bávaro, Cap Cana, Uvero Alto…',
    },
  },
  interests: {
    beach_island: { label: 'Beaches & islands', emoji: '🏝️' },
    snorkel_reef: { label: 'Snorkelling & reefs', emoji: '🤿' },
    wildlife: { label: 'Animals & wildlife', emoji: '🐒' },
    adrenaline: { label: 'Adrenaline & speed', emoji: '🪂' },
    offroad: { label: 'Off-road & jungle', emoji: '🚙' },
    culture: { label: 'Culture & history', emoji: '🏛️' },
    nightlife: { label: 'Nightlife & shows', emoji: '🪩' },
    food_drink: { label: 'Food & drinks', emoji: '🍤' },
    views_photo: { label: 'Views & photos', emoji: '📸' },
    relax: { label: 'Slow & relaxing', emoji: '🧘' },
  },
  slots: {
    full: 'Full day · early start',
    half: 'Half day',
    short: 'Short escape',
    evening: 'After dark',
  },
  result: {
    eyebrow: 'Your plan',
    dayLabel: (n: number) => `Day ${n}`,
    hours: (h: number) => `≈ ${h} h`,
    whyFits: 'Why this fits you',
    heads: 'Heads up',
    swap: 'Swap',
    remove: 'Remove',
    add: 'Add to plan',
    alternates: 'Also strong for you',
    alternatesHint: 'Tap to add — the planner keeps the timing honest.',
    priceFor: (adults: number, children: number) => {
      const adultPart = `${adults} ${adults === 1 ? 'adult' : 'adults'}`;
      return children > 0
        ? `${adultPart} · ${children} ${children === 1 ? 'child' : 'children'}`
        : adultPart;
    },
    building: 'Building your day…',
    dayTotal: 'Day total',
    dayFull: 'Your own pick fills this day — anything else would not fit the clock.',
    daysLabel: 'Days in this plan',
    addDay: 'Add a day',
    removeDay: 'Remove the last day',
    reviewTitle: 'Nothing is booked yet',
    reviewBody:
      'Your plan goes to Francisco on WhatsApp. He reads it personally, checks the timings and availability with each operator, and replies to confirm whether the day works as planned — or suggests the fix. A payment link only follows once the plan is confirmed.',
    addedByYou: 'Added by you',
    grandTotal: 'Plan total',
    perPerson: 'per person',
    budgetOk: 'Inside your budget',
    budgetOver: 'Above the budget you set — swap or drop something, or keep it if it is worth it.',
    transportTitle: 'Getting around',
    transportIncluded: 'Hotel pick-up and drop-off is included with every excursion in this plan.',
    transportQuote: 'Private transport is quoted separately — Francisco confirms the exact rate on WhatsApp.',
    vehicleSuggestion: (label: string, pax: number) => `Suggested vehicle for ${pax}: ${label}`,
    openCalculator: 'Open the transfer calculator',
    book: 'Send this plan on WhatsApp',
    bookHint: 'Opens WhatsApp with your full itinerary written out. Nothing is charged.',
    viewDetails: 'Tour details',
    empty: 'No excursion matched every filter. Loosen a constraint or raise the budget and we will find something.',
    ruledOut: 'Left out on purpose',
    childRate: 'child rate applied',
    adultRateForKids: 'no child rate on this tour — children are priced as adults',
    tier: 'Ticket',
    replan: 'Rebuild from my answers',
    savedNote: 'Your answers stay on this device only.',
  },
  reasons: {
    interest: (list: string) => `Hits your interest in ${list}`,
    energy: (n: number) => `Intensity ${n}/5 — matches the pace you asked for`,
    audience: (party: string) => `Consistently loved by ${party}`,
    kids: (age: number) => `Works for children from about ${age} years`,
    kidsMagnet: 'Kids remember this one for years',
    budget: (price: number) => `$${price} per person — comfortably inside your budget`,
    aim: (aim: string) => `Delivers on “${aim}”`,
    occasion: (occasion: string) => `A classic for a ${occasion}`,
    gentle: 'Easy on the body — no scrambling or rough terrain',
    signature: 'One of Francisco’s signature days',
    variety: 'Adds a completely different flavour to your plan',
  },
  cautions: {
    boat: 'Long boat crossing — bring a remedy if anyone gets sea-sick',
    water: 'Includes real swimming time',
    early: 'Early pick-up, usually around sunrise',
    long: (h: number) => `Long day out — about ${h} hours door to door`,
    mobility: 'Physically demanding terrain',
    minAge: (n: number) => `Minimum age ${n}`,
    adults: 'Adults only (18+)',
    alcohol: 'Open bar included',
    overBudget: 'Above your per-day budget on its own',
  },
  parties: {
    solo: 'solo travellers',
    couple: 'couples',
    family: 'families',
    friends: 'friends groups',
    multigen: 'multi-generation groups',
  },
  occasions: {
    none: 'trip',
    honeymoon: 'honeymoon',
    anniversary: 'anniversary',
    birthday: 'birthday',
    bachelor: 'bachelor party',
    reunion: 'family reunion',
  },
  aims: {
    stories: 'stories to tell',
    unwind: 'deep rest',
    together: 'time together',
    adrenaline: 'a racing heart',
    romance: 'romance',
    discover: 'the real island',
    party: 'a legendary night',
  },
  personas: {
    reef_chaser: { emoji: '🤿', title: 'The Reef Chasers', blurb: 'Masks on before the coffee is finished. Your day belongs to the water.' },
    slow_romantic: { emoji: '💞', title: 'Slow-Living Romantics', blurb: 'Two people, one hammock, and a lobster lunch with nowhere to be.' },
    thrill_seeker: { emoji: '⚡', title: 'The Full-Send Crew', blurb: 'Mud, heights and speed. You will sleep extremely well tonight.' },
    family_explorer: { emoji: '🐒', title: 'The Explorer Family', blurb: 'Monkeys on shoulders, sand in everything, zero screens all day.' },
    night_legend: { emoji: '🪩', title: 'Kings of the Night', blurb: 'The day is a warm-up. The island’s best stage is waiting after dark.' },
    culture_seeker: { emoji: '🏛️', title: 'The Island Historians', blurb: 'Cobblestones, cacao and the stories behind the postcard.' },
    island_dreamer: { emoji: '🏝️', title: 'The Island Dreamers', blurb: 'Turquoise, starfish, a long buffet lunch and absolutely no rush.' },
    gentle_wanderer: { emoji: '🕊️', title: 'The Gentle Wanderers', blurb: 'Beautiful places, comfortable pace, everything within easy reach.' },
    crew_of_legends: { emoji: '🥂', title: 'The Legendary Crew', blurb: 'One boat, one playlist, one group chat that will not stop.' },
    all_rounder: { emoji: '🌴', title: 'The All-Rounders', blurb: 'A bit of everything the coast does best, balanced across the day.' },
  },
  whatsapp: {
    intro: (brand: string) => `Hi! I built a day plan on ${brand} 🌴`,
    profile: 'My group',
    plan: 'The plan',
    total: 'Estimated total',
    transport: 'Transport',
    date: 'Preferred start',
    zone: 'Pick-up',
    closing:
      'Could you check that this day is actually feasible, confirm availability and the final price, and then send me the payment link?',
  },
};

type CopyShape = typeof en;

const es: CopyShape = {
  tab: 'Planea',
  hero: {
    eyebrow: 'Planificador personal',
    title: 'Cuéntanos quién eres.\nDiseñamos el día.',
    subtitle:
      'Unas preguntas rápidas sobre tu grupo, tu energía y tu presupuesto — y el planificador de Francisco arma un itinerario real desde el catálogo en vivo, con precios para tu grupo exacto.',
    start: 'Empezar a planear',
    resume: 'Retomar mi plan',
    browse: 'Prefiero ver el catálogo',
    minutes: '≈ 90 segundos · 12 preguntas · sin registro',
    bullets: [
      { emoji: '🧭', title: 'Lee a tu grupo', text: 'Edades, energía, nadadores, madrugadores — todo define la selección.' },
      { emoji: '🧮', title: 'Precios reales', text: 'Cada tour se calcula desde el catálogo real para tus adultos y niños.' },
      { emoji: '🗓️', title: 'Un día que funciona', text: 'Nunca dos tours de 10 horas el mismo día. Horarios y ritmo cuadran.' },
    ],
  },
  ui: {
    back: 'Atrás',
    next: 'Continuar',
    skip: 'Omitir',
    stepOf: (a: number, b: number) => `Paso ${a} de ${b}`,
    startOver: 'Empezar de nuevo',
    editAnswers: 'Editar respuestas',
    yourProfile: 'Tu perfil',
    seePlan: 'Armar mi día',
    optional: 'Opcional',
    pickUpTo: (n: number) => `Elige hasta ${n}`,
    pickAtLeastOne: 'Elige al menos una para continuar',
    selected: 'Elegido',
    adults: 'Adultos',
    children: 'Niños',
    kidsAges: '¿Qué edades tienen los niños?',
    tapToEdit: 'Toca cualquier etiqueta para cambiar tu respuesta',
    keyboardHint: 'Tip: presiona 1–9 para elegir, Enter para continuar',
  },
  questions: {
    partyType: {
      title: '¿Quién viene al Caribe?',
      hint: 'Esto define desde el tipo de barco hasta cuán largo debe ser el día.',
      options: {
        solo: { label: 'Solo yo', desc: 'Viajero solo, libre de decir que sí a todo', emoji: '🧍' },
        couple: { label: 'Nosotros dos', desc: 'Una pareja compartiendo el día', emoji: '💞' },
        family: { label: 'Familia con niños', desc: 'Padres y niños a bordo', emoji: '👨‍👩‍👧' },
        friends: { label: 'Grupo de amigos', desc: 'Un grupo que viaja con volumen', emoji: '🥂' },
        multigen: { label: 'Varias generaciones', desc: 'Abuelos, padres y niños juntos', emoji: '👵' },
      },
    },
    headcount: {
      title: '¿Cuántos son?',
      hint: 'Los precios se calculan por persona, con tarifa de niño real donde el tour la ofrece.',
    },
    adultAge: {
      title: '¿En qué franja de edad están los adultos?',
      hint: 'Nadie pide identificación — solo ajusta ritmo y comodidad.',
      options: {
        young: { label: '18 – 29', desc: 'Bienvenidas las noches largas', emoji: '🔥' },
        prime: { label: '30 – 44', desc: 'Aventura de día, buena cena de noche', emoji: '🌞' },
        mature: { label: '45 – 59', desc: 'Grandes experiencias, logística cómoda', emoji: '🌴' },
        senior: { label: '60 +', desc: 'Belleza y comodidad antes que terreno duro', emoji: '🕊️' },
      },
    },
    energy: {
      title: '¿Cuán salvaje debe ser el día?',
      hint: 'Desde hamaca lenta hasta pura adrenalina.',
      scale: [
        { label: 'Descalzo y lento', desc: 'Arena, sombra, almuerzos largos' },
        { label: 'Tranquilo', desc: 'Actividad suave y mucho descanso' },
        { label: 'Equilibrado', desc: 'Un poco de emoción, un poco de calma' },
        { label: 'Bastante aventurero', desc: 'Barro, velocidad, alturas' },
        { label: 'A todo dar', desc: 'Máxima adrenalina, mínimo sentarse' },
      ],
    },
    interests: {
      title: '¿Qué te atrae más?',
      hint: 'Elige hasta cinco. Es lo que más pesa en la selección.',
    },
    aim: {
      title: '¿Qué quieres llevarte a casa?',
      hint: 'La sensación que más importa al regresar.',
      options: {
        stories: { label: 'Historias que contar', desc: 'Días que se cuentan por años', emoji: '📖' },
        unwind: { label: 'Descanso profundo', desc: 'Volver realmente recargado', emoji: '🧘' },
        together: { label: 'Tiempo juntos', desc: 'Que el grupo conecte de verdad', emoji: '🫶' },
        adrenaline: { label: 'El corazón a mil', desc: 'Adrenalina que aún se siente', emoji: '⚡' },
        romance: { label: 'Romance', desc: 'Solo ustedes dos, perfecto', emoji: '💫' },
        discover: { label: 'La isla real', desc: 'Cultura, gente, sabores', emoji: '🧭' },
        party: { label: 'Una noche legendaria', desc: 'Música y baile hasta tarde', emoji: '🪩' },
      },
    },
    dayShape: {
      title: '¿Qué tan lleno debe sentirse el día?',
      hint: 'Solo combinamos experiencias cuando los horarios realmente cuadran.',
      options: {
        signature: { label: 'Una experiencia estrella', desc: 'Una sola excursión inolvidable, sin prisa', emoji: '💎' },
        balanced: { label: 'Dos por día', desc: 'Un evento principal más otro momento', emoji: '⚖️' },
        packed: { label: 'Tres por día', desc: 'Mañana, tarde y noche en movimiento', emoji: '🔋' },
        max: { label: 'Llénalo', desc: 'Todo lo que el reloj permita', emoji: '🚀' },
      },
    },
    days: {
      title: '¿Cuántos días planeamos?',
      hint: 'Más días significa más variedad — nunca la misma costa dos veces.',
      unit: 'días',
    },
    budget: {
      title: '¿Qué es cómodo por persona, por día?',
      hint: 'Solo entradas de excursión. Nada se infla encima.',
      options: {
        value: { label: 'Hasta $80', desc: 'La mejor relación calidad-precio', emoji: '🌱' },
        balanced: { label: '$80 – $150', desc: 'El punto justo para la mayoría', emoji: '⭐' },
        premium: { label: '$150 – $260', desc: 'Categorías premium, áreas VIP, langosta', emoji: '👑' },
        open: { label: 'Presupuesto abierto', desc: 'Muéstrame lo mejor sin límite', emoji: '💎' },
      },
    },
    transport: {
      title: '¿Cómo quieres moverte?',
      hint: 'Toda excursión ya incluye recogida en el hotel. Lo privado es una mejora.',
      options: {
        included: { label: 'Recogida compartida', desc: 'Traslado incluido con el grupo del tour', emoji: '🚐' },
        private_day: { label: 'Vehículo privado por el día', desc: 'Tu chofer esperando entre paradas', emoji: '🚙' },
        private_full: { label: 'Todo privado', desc: 'Aeropuerto, regreso y cada día de excursión', emoji: '🛬' },
      },
    },
    constraints: {
      title: '¿Algo que debamos tener en cuenta?',
      hint: 'Ser honesto mejora el plan. Omite si no aplica nada.',
      options: {
        non_swimmer: { label: 'Nadadores débiles', desc: 'Que nadar en profundo sea opcional', emoji: '🛟' },
        seasick: { label: 'Mareo en barco', desc: 'Evitar travesías largas', emoji: '🌊' },
        limited_mobility: { label: 'Movilidad limitada', desc: 'Sin senderos duros ni escalar', emoji: '🦯' },
        no_early: { label: 'Nada de madrugar', desc: 'Sin salidas al amanecer', emoji: '⏰' },
        no_alcohol: { label: 'Sin alcohol', desc: 'Las barras libres importan menos', emoji: '🚫' },
        early_nights: { label: 'Noches tempranas', desc: 'Nada que termine tardísimo', emoji: '🌙' },
        sun_sensitive: { label: 'Sensibles al sol', desc: 'Preferimos sombra y menos exposición', emoji: '🧴' },
      },
    },
    occasion: {
      title: '¿Celebramos algo?',
      hint: 'A Francisco le gusta saberlo — cambia los detalles.',
      options: {
        none: { label: 'Solo un gran viaje', desc: 'Sin ocasión especial', emoji: '🌴' },
        honeymoon: { label: 'Luna de miel', desc: 'Recién casados en el mar', emoji: '💍' },
        anniversary: { label: 'Aniversario', desc: 'Celebrando los años juntos', emoji: '🥂' },
        birthday: { label: 'Cumpleaños', desc: 'Alguien cumple un año más valiente', emoji: '🎂' },
        bachelor: { label: 'Despedida de soltero/a', desc: 'La última gran fiesta', emoji: '🎉' },
        reunion: { label: 'Reunión familiar', desc: 'Todos en un mismo lugar por fin', emoji: '🏡' },
      },
    },
    logistics: {
      title: 'Últimos detalles',
      hint: 'Ambos opcionales — solo aceleran la respuesta de Francisco.',
      dateLabel: 'Primer día del plan',
      zoneLabel: 'Hotel o zona',
      zonePlaceholder: 'ej. Bávaro, Cap Cana, Uvero Alto…',
    },
  },
  interests: {
    beach_island: { label: 'Playas e islas', emoji: '🏝️' },
    snorkel_reef: { label: 'Snorkel y arrecifes', emoji: '🤿' },
    wildlife: { label: 'Animales y naturaleza', emoji: '🐒' },
    adrenaline: { label: 'Adrenalina y velocidad', emoji: '🪂' },
    offroad: { label: 'Todoterreno y selva', emoji: '🚙' },
    culture: { label: 'Cultura e historia', emoji: '🏛️' },
    nightlife: { label: 'Vida nocturna y shows', emoji: '🪩' },
    food_drink: { label: 'Comida y bebida', emoji: '🍤' },
    views_photo: { label: 'Vistas y fotos', emoji: '📸' },
    relax: { label: 'Calma y relax', emoji: '🧘' },
  },
  slots: {
    full: 'Día completo · salida temprano',
    half: 'Medio día',
    short: 'Escapada corta',
    evening: 'Al caer la noche',
  },
  result: {
    eyebrow: 'Tu plan',
    dayLabel: (n: number) => `Día ${n}`,
    hours: (h: number) => `≈ ${h} h`,
    whyFits: 'Por qué encaja contigo',
    heads: 'Ten en cuenta',
    swap: 'Cambiar',
    remove: 'Quitar',
    add: 'Añadir al plan',
    alternates: 'También ideales para ti',
    alternatesHint: 'Toca para añadir — el planificador cuida los horarios.',
    priceFor: (adults: number, children: number) => {
      const adultPart = `${adults} ${adults === 1 ? 'adulto' : 'adultos'}`;
      return children > 0
        ? `${adultPart} · ${children} ${children === 1 ? 'niño' : 'niños'}`
        : adultPart;
    },
    building: 'Armando tu día…',
    dayTotal: 'Total del día',
    dayFull: 'Tu elección llena este día — cualquier otra cosa no cabría en el reloj.',
    daysLabel: 'Días en este plan',
    addDay: 'Añadir un día',
    removeDay: 'Quitar el último día',
    reviewTitle: 'Todavía no hay nada reservado',
    reviewBody:
      'Tu plan le llega a Francisco por WhatsApp. Él lo revisa personalmente, verifica horarios y disponibilidad con cada operador, y responde para confirmar si el día funciona tal cual — o propone el ajuste. El enlace de pago solo llega cuando el plan está confirmado.',
    addedByYou: 'Añadido por ti',
    grandTotal: 'Total del plan',
    perPerson: 'por persona',
    budgetOk: 'Dentro de tu presupuesto',
    budgetOver: 'Por encima del presupuesto que fijaste — cambia o quita algo, o déjalo si vale la pena.',
    transportTitle: 'Cómo se mueven',
    transportIncluded: 'La recogida y regreso al hotel está incluida en cada excursión de este plan.',
    transportQuote: 'El transporte privado se cotiza aparte — Francisco confirma la tarifa exacta por WhatsApp.',
    vehicleSuggestion: (label: string, pax: number) => `Vehículo sugerido para ${pax}: ${label}`,
    openCalculator: 'Abrir la calculadora de traslados',
    book: 'Enviar este plan por WhatsApp',
    bookHint: 'Abre WhatsApp con tu itinerario completo escrito. No se cobra nada.',
    viewDetails: 'Detalles del tour',
    empty: 'Ninguna excursión pasó todos los filtros. Suelta una restricción o sube el presupuesto y encontraremos algo.',
    ruledOut: 'Dejado fuera a propósito',
    childRate: 'tarifa de niño aplicada',
    adultRateForKids: 'este tour no tiene tarifa de niño — se cobran como adultos',
    tier: 'Entrada',
    replan: 'Rehacer desde mis respuestas',
    savedNote: 'Tus respuestas quedan solo en este dispositivo.',
  },
  reasons: {
    interest: (list: string) => `Conecta con tu interés en ${list}`,
    energy: (n: number) => `Intensidad ${n}/5 — coincide con el ritmo que pediste`,
    audience: (party: string) => `Siempre funciona con ${party}`,
    kids: (age: number) => `Apto para niños desde unos ${age} años`,
    kidsMagnet: 'Los niños lo recuerdan por años',
    budget: (price: number) => `$${price} por persona — cómodo dentro de tu presupuesto`,
    aim: (aim: string) => `Cumple con “${aim}”`,
    occasion: (occasion: string) => `Un clásico para ${occasion}`,
    gentle: 'Suave con el cuerpo — sin terreno difícil',
    signature: 'Uno de los días insignia de Francisco',
    variety: 'Aporta un sabor totalmente distinto al plan',
  },
  cautions: {
    boat: 'Travesía larga en barco — lleva algo si alguien se marea',
    water: 'Incluye tiempo real de natación',
    early: 'Recogida temprano, normalmente al amanecer',
    long: (h: number) => `Día largo — unas ${h} horas puerta a puerta`,
    mobility: 'Terreno físicamente exigente',
    minAge: (n: number) => `Edad mínima ${n} años`,
    adults: 'Solo adultos (18+)',
    alcohol: 'Barra libre incluida',
    overBudget: 'Por sí solo supera tu presupuesto diario',
  },
  parties: {
    solo: 'viajeros solos',
    couple: 'parejas',
    family: 'familias',
    friends: 'grupos de amigos',
    multigen: 'grupos de varias generaciones',
  },
  occasions: {
    none: 'viaje',
    honeymoon: 'luna de miel',
    anniversary: 'aniversario',
    birthday: 'cumpleaños',
    bachelor: 'despedida de soltero',
    reunion: 'reunión familiar',
  },
  aims: {
    stories: 'historias que contar',
    unwind: 'descanso profundo',
    together: 'tiempo juntos',
    adrenaline: 'el corazón a mil',
    romance: 'romance',
    discover: 'la isla real',
    party: 'una noche legendaria',
  },
  personas: {
    reef_chaser: { emoji: '🤿', title: 'Cazadores de Arrecife', blurb: 'Máscara puesta antes de terminar el café. El día es del agua.' },
    slow_romantic: { emoji: '💞', title: 'Románticos sin Prisa', blurb: 'Dos personas, una hamaca y langosta sin hora de regreso.' },
    thrill_seeker: { emoji: '⚡', title: 'Escuadrón a Todo Dar', blurb: 'Barro, altura y velocidad. Esta noche dormirán muy bien.' },
    family_explorer: { emoji: '🐒', title: 'La Familia Exploradora', blurb: 'Monos en el hombro, arena por todos lados, cero pantallas.' },
    night_legend: { emoji: '🪩', title: 'Reyes de la Noche', blurb: 'El día es el calentamiento. El mejor escenario abre al anochecer.' },
    culture_seeker: { emoji: '🏛️', title: 'Historiadores de la Isla', blurb: 'Adoquines, cacao y las historias detrás de la postal.' },
    island_dreamer: { emoji: '🏝️', title: 'Soñadores de Isla', blurb: 'Turquesa, estrellas de mar, buffet largo y ninguna prisa.' },
    gentle_wanderer: { emoji: '🕊️', title: 'Viajeros Serenos', blurb: 'Lugares hermosos, ritmo cómodo, todo al alcance.' },
    crew_of_legends: { emoji: '🥂', title: 'La Tripulación Legendaria', blurb: 'Un barco, una playlist y un grupo que no para.' },
    all_rounder: { emoji: '🌴', title: 'Los Todoterreno', blurb: 'Un poco de todo lo mejor de la costa, bien repartido.' },
  },
  whatsapp: {
    intro: (brand: string) => `¡Hola! Armé un plan de día en ${brand} 🌴`,
    profile: 'Mi grupo',
    plan: 'El plan',
    total: 'Total estimado',
    transport: 'Transporte',
    date: 'Fecha preferida',
    zone: 'Recogida',
    closing:
      '¿Puedes revisar si este día es realmente factible, confirmar disponibilidad y el precio final, y luego enviarme el enlace de pago?',
  },
};

export const plannerCopy = { en, es } as const;

export type PlannerCopy = CopyShape;

export const getPlannerCopy = (locale: string): PlannerCopy =>
  locale.startsWith('es') ? es : en;
