/**
 * apply-seo.mjs — rewrites the SEO block in index.html and the Sitemap line in
 * robots.txt from the resolved brand name and site URL.
 *
 * index.html is static, but the company name lives in brand.json, so the two
 * used to drift: the page shipped a hardcoded company in its title, OpenGraph
 * tags and structured data no matter what the site was actually called. This
 * runs in `npm run build`, after populate-local-data has refreshed brand.json,
 * so a rename in the admin panel reaches search engines on the next deploy.
 *
 * Only the delimited block is touched. Everything outside it — charset,
 * viewport, favicons, preconnects, the app mount — is left exactly as authored.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { ROOT, resolveSiteConfig } from './site-config.mjs';

const INDEX_PATH = join(ROOT, 'index.html');
const ROBOTS_PATH = join(ROOT, 'public', 'robots.txt');

const BEGIN = '<!-- seo:begin — generated by scripts/apply-seo.mjs, do not edit by hand -->';
const END = '<!-- seo:end -->';

/** Escapes text going into an HTML attribute. */
const attr = (value) =>
  String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

/** JSON-LD is embedded in a <script>, so `</` must not close it early. */
const jsonLd = (value) => JSON.stringify(value, null, 2).replace(/<\//g, '<\\/');

const buildSeoBlock = ({ siteUrl, brandName, description, shortDescription, locales }) => {
  const title = `${brandName} — Caribbean Tours & Excursions in Punta Cana`;
  const pages = [
    { path: '/', name: 'Home' },
    { path: '/tours', name: 'Tours' },
    { path: '/transport', name: 'Transportation' },
    { path: '/blog', name: 'Blog' },
    { path: '/contact', name: 'Contact' },
  ];

  const organization = {
    '@context': 'https://schema.org',
    '@type': 'TravelAgency',
    name: brandName,
    url: siteUrl,
    image: `${siteUrl}/og-image.jpg`,
    description: shortDescription,
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'El Cortecito, Bávaro',
      addressLocality: 'Punta Cana',
      addressRegion: 'La Altagracia',
      postalCode: '23000',
      addressCountry: 'DO',
    },
    geo: { '@type': 'GeoCoordinates', latitude: '18.6945', longitude: '-68.4156' },
    priceRange: '$$',
    availableLanguage: ['en', 'es'],
    openingHoursSpecification: [
      {
        '@type': 'OpeningHoursSpecification',
        dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        opens: '07:00',
        closes: '19:00',
      },
    ],
  };

  const breadcrumbs = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: pages.map((page, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: page.name,
      item: `${siteUrl}${page.path}`,
    })),
  };

  const websiteSearch = {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: brandName,
    url: siteUrl,
    inLanguage: locales,
  };

  const alternates = locales
    .map((lang) => `    <link rel="alternate" hreflang="${lang}" href="${attr(`${siteUrl}/?lang=${lang}`)}" />`)
    .join('\n');

  return `${BEGIN}
    <title>${attr(title)}</title>
    <meta name="description" content="${attr(description)}" />
    <meta name="author" content="${attr(brandName)}" />
    <meta name="publisher" content="${attr(brandName)}" />
    <meta name="keywords" content="${attr(`${brandName}, Punta Cana tours, Dominican Republic excursions, island trips, buggy tours, horseback riding, water sports, Bavaro adventures, Punta Cana tourism`)}" />

    <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" />
    <meta name="googlebot" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" />

    <link rel="canonical" href="${attr(siteUrl)}" />
${alternates}
    <link rel="alternate" hreflang="x-default" href="${attr(siteUrl)}" />

    <meta property="og:title" content="${attr(title)}" />
    <meta property="og:description" content="${attr(shortDescription)}" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="${attr(siteUrl)}" />
    <meta property="og:image" content="${attr(`${siteUrl}/og-image.jpg`)}" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:site_name" content="${attr(brandName)}" />
    <meta property="og:locale" content="en_US" />
    <meta property="og:locale:alternate" content="es_DO" />

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${attr(title)}" />
    <meta name="twitter:description" content="${attr(shortDescription)}" />
    <meta name="twitter:image" content="${attr(`${siteUrl}/og-image.jpg`)}" />

    <meta name="geo.region" content="DO-11" />
    <meta name="geo.placename" content="Punta Cana" />
    <meta name="geo.position" content="18.6945;-68.4156" />
    <meta name="ICBM" content="18.6945, -68.4156" />

    <script type="application/ld+json">
${jsonLd(organization)}
    </script>
    <script type="application/ld+json">
${jsonLd(breadcrumbs)}
    </script>
    <script type="application/ld+json">
${jsonLd(websiteSearch)}
    </script>
${END}`;
};

const applyToIndex = async (config) => {
  const html = await readFile(INDEX_PATH, 'utf-8');
  const start = html.indexOf(BEGIN);
  const end = html.indexOf(END);
  if (start === -1 || end === -1) {
    throw new Error(
      `index.html has no "${BEGIN}" … "${END}" block. Restore the markers so ` +
        'the generated SEO tags have somewhere to go.'
    );
  }
  const next = html.slice(0, start) + buildSeoBlock(config) + html.slice(end + END.length);
  if (next === html) {
    console.log('[apply-seo] index.html already up to date');
    return;
  }
  await writeFile(INDEX_PATH, next, 'utf-8');
  console.log('[apply-seo] index.html SEO block rewritten');
};

const applyToRobots = async ({ siteUrl }) => {
  const robots = await readFile(ROBOTS_PATH, 'utf-8');
  const next = robots.replace(/^Sitemap:.*$/m, `Sitemap: ${siteUrl}/sitemap.xml`);
  if (next === robots) {
    console.log('[apply-seo] robots.txt already up to date');
    return;
  }
  await writeFile(ROBOTS_PATH, next, 'utf-8');
  console.log(`[apply-seo] robots.txt sitemap → ${siteUrl}/sitemap.xml`);
};

const main = async () => {
  const config = await resolveSiteConfig();
  console.log(`[apply-seo] brand "${config.brandName}" at ${config.siteUrl}`);
  await applyToIndex(config);
  await applyToRobots(config);
};

main().catch((error) => {
  console.error('[apply-seo] failed:', error.message);
  process.exit(1);
});
